modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/CodenameRevy/-1.14.4-MagicMirror/issues"

[[mods]]
modId="magicmirror"
version="1.0.2.2"
displayName="Magic Mirrors"
displayURL="https://github.com/CodenameRevy/-1.14.4-MagicMirror"
logoFile="logo.png"
credits="MichaelLimaRodrigues" #optional
authors="CodenameRevy"
description='''
Magic Mirror mod adds several new items that are used to teleport you to your bed location almost instantly!

Update 1.0.2.2 changelog:

-Added Items to circumvent using the mod in existing worlds:
     -Enchanted Mirror (Nether Star (Center), 2 Glass panes(Above and below Nether Star), 6 Nether Quartz (All around))
     -Mirror Frame (Iron Ingot in center and Iron Nuggets all around)
     -Magic Mirror is crafted with Mirror Frame, Redstone and Enchanted Mirror in that order
     -Only the Main Magic Mirror can be crafted, the other Biome based aren't available with this method

-Brazilian Portuguese translation by MichaelLimaRodrigues

-Bugfixes:
     -Fixed Igloo chest loot table;
     -Capitalization typo;
'''

[[dependencies.magicmirror]]
    modId="forge"
    mandatory=true
    versionRange="[28.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.magicmirror]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
