modLoader="javafml"
loaderVersion="[30,)"
issueTrackerURL="https://github.com/CodenameRevy/MagicMirrors/issues"

[[mods]]
modId="magicmirror"
version="1.0.3.6"
displayName="Magic Mirrors"
displayURL="https://github.com/CodenameRevy/MagicMirrors"
logoFile="logo.png"
credits="MichaelLimaRodrigues"
authors="CodenameRevy"
description='''
Magic Mirror mod adds several new items that are used to teleport you to your bed location almost instantly!

Update 1.0.3.6 (1.15.1) changelog:

- Updated to Forge 30.0.15
- Updated Mappings to 20191222-1.14.3

[Internal Changes]
- Fixed some weird function names :P
'''

[[dependencies.magicmirror]]
    modId="forge"
    mandatory=true
    versionRange="[30,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.magicmirror]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.1]"
    ordering="NONE"
    side="BOTH"
