license="MIT License"
modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/CodenameRevy/MagicMirrors/issues"

[[mods]]
modId="magicmirror"
version="${file.jarVersion}"
displayName="Magic Mirrors"
displayURL="codenamerevy.github.io"
logoFile="logo.png"
credits='''
CodenameRevy (Mod developer),
MichaelLimaRodrigues (Brazilian Portuguese translations)
Sn4pe (Spanish translations)
DirectorX (Russian translations)'''
authors="CodenameRevy"
description='''
Magic Mirror mod adds several new items that are used to teleport you to your bed location almost instantly!
'''

[[dependencies.magicmirror]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.magicmirror]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
